portal/src/main/java/org/satuban/tangoportal/portal/model/entity/School.java
package org.satuban.tangoportal.portal.model.entity;

import lombok.Data;
import org.satuban.tangoportal.portal.dao.common.Column;
import org.satuban.tangoportal.portal.dao.common.Table;

/**
 * Created by Artur on 16.05.2017.
 */
@Table
@Data
public class School implements BaseEntity {
    private static final long serialVersionUID = -5829244800732228439L;

    private Long id;
    @Column
    private String name;
    @Column
    private String workPhone;
    @Column
    private String mobilePhone;
    @Column
    private Long addressId;
    @Column
    private String siteUrl;
    @Column
    private String fbUrl;
    @Column
    private String vkUrl;
    @Column
    private Integer defaultDuration;
    @Column
    private long userId;
    @Column
    private String photo;
}

portal/src/main/java/org/satuban/tangoportal/portal/model/entity/User.java
package org.satuban.tangoportal.portal.model.entity;

import lombok.Data;
import org.satuban.tangoportal.portal.dao.common.Column;
import org.satuban.tangoportal.portal.dao.common.Table;
import org.satuban.tangoportal.portal.model.dto.Roles;
import org.satuban.tangoportal.portal.model.enums.Role;
import org.satuban.tangoportal.portal.model.enums.UserStatus;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * Created by Artur on 20.05.2017.
 */
@Table(name = "user_profile")
@Data
public class User implements UserDetails, BaseEntity {
    private static final long serialVersionUID = -1824698976916331722L;

    private Long id;
    @Column
    private String username;
    @Column
    private String password;
    @Column
    private String firstName;
    @Column
    private String secondName;
    @Column
    private String fbProfile;
    @Column
    private String vkProfile;
    @Column
    private Long cityId;
    @Column
    private String avatar;
    @Column
    private boolean dj;
    @Column
    private boolean teacher;
    @Column
    private boolean schoolLead;
    @Column
    private boolean organizer;
    @Column
    private boolean photographer;
    @Column
    private boolean schoolAdmin;
    @Column
    private boolean couturier;
    @Column
    private boolean admin;
    @Column
    private String inviteToken;
    @Column
    private UserStatus status = UserStatus.INACTIVE;
    @Column
    private long invitedBy;
    @Column
    private String djNick;
    @Column
    private String language = "ru";

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        List<GrantedAuthority> list = new ArrayList<>();

        list.add(new SimpleGrantedAuthority(Role.USER.role()));

        return list;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return status != UserStatus.INACTIVE;
    }

    public void setRoles(Roles roles) {
        dj = roles.isDj();
        schoolLead = roles.isSchoolLead();
        photographer = roles.isPhotographer();
        organizer = roles.isOrganizer();
        teacher = roles.isTeacher();
        couturier = roles.isCouturier();
        schoolAdmin = roles.isSchoolAdmin();
        admin = roles.isAdmin();
    }

    public String getFullName() {
        return firstName + " " + secondName;
    }
}

portal/src/main/java/org/satuban/tangoportal/portal/model/enums/MapType.java
package org.satuban.tangoportal.portal.model.enums;

/**
 * Created by Artur on 17.08.2017.
 */
public enum MapType {
    EVENT,
    SCHOOL,
    DJ
}

portal/src/main/java/org/satuban/tangoportal/portal/model/enums/SiteMapType.java
package org.satuban.tangoportal.portal.model.enums;

/**
 * Created by Danilov on 21.08.2017.
 */
public enum  SiteMapType {
    SCHOOLS, DJS;
}

portal/src/main/java/org/satuban/tangoportal/portal/web/controller/SiteMapController.java
package org.satuban.tangoportal.portal.web.controller;

import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.TemplateException;
import org.satuban.tangoportal.portal.service.SiteMapService;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * Created by Danilov on 21.08.2017.
 */
@Controller
public class SiteMapController {
    private final SiteMapService siteMapService;
    private final Configuration configuration;

    public SiteMapController(SiteMapService siteMapService,
                             Configuration configuration) {
        this.siteMapService = siteMapService;
        this.configuration = configuration;
    }

    @RequestMapping(value = "/sitemap.xml", method = RequestMethod.GET)
    public void getSiteMapXml (HttpServletRequest request, HttpServletResponse response, Model model) throws IOException, TemplateException {
        model.addAttribute("cities", siteMapService.getCities("http://"
                + request.getServerName()));

        Template siteMapTemplate = configuration.getTemplate("sitemap.ftl");

        siteMapTemplate.process(model, response.getWriter());
    }
}

portal/src/main/resources/ftl/about.ftl
<#ftl encoding="UTF-8">

<#include "template.ftl"/>
<#import "spring.ftl" as spring/>

<#macro page_content>
<div class="wrapper" id="index">
    <div class="container">

        <div class="main main-raised">
            <div class="row">
                <div class="container-fluid">
                    <div class="col-md-12">
                        <h2 class="title"><@spring.message "page.title.about"/></h2>
                        <p>
                            <@spring.message "page.about.content1"/>
                        </p>
                        <h3 class="title"><@spring.message "page.about.subtitle1"/></h3>
                        <p>
                            <@spring.message "page.about.content2"/>
                        </p>
                        <p>
                            <@spring.message "page.about.content3"/>
                        </p>
                        <p>
                            <@spring.message "page.about.content4"/>
                        </p>

                        <h3 class="title"><@spring.message "page.about.subtitle2"/></h3>
                        <p>
                            <@spring.message "page.about.content5"/>
                        </p>
                        <p>
                            <@spring.message "page.about.content6"/>
                        </p>
                        <p>
                            <@spring.message "page.about.content7"/>
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

</#macro>

<@display_page />

portal/src/main/resources/ftl/cabinet.ftl
<#ftl encoding="UTF-8">

<#include "template.ftl"/>
<#include "util.ftl"/>


<#macro components>
    <#include "components/form.ftl"/>
    <#include "components/teacherList.ftl"/>
    <#include "components/profileModal.ftl"/>
    <#include "components/schoolModal.ftl"/>
    <#include "components/eventModal.ftl"/>
    <#include "components/regularLessonModal.ftl"/>
    <#include "components/singleLessonModal.ftl"/>
    <#include "components/practiceModal.ftl"/>
    <#include "components/changePasswordModal.ftl"/>
    <#include "components/roomList.ftl"/>
    <#include "components/referralList.ftl"/>
    <#include "components/milongas.ftl"/>
    <#include "components/eventTab.ftl"/>
    <#include "components/adminTab.ftl"/>

</#macro>

<#macro page_content>
<div class="wrapper" id="cabinet" v-cloak>
    <div class="container">
        <div class="main main-raised">

            <ul class="nav nav-pills nav-pills-icons" role="tablist">
                <li class="active">
                    <a href="#profileTab" role="tab" data-toggle="tab" aria-expanded="false">
                        <i class="material-icons">account_box</i>
                        <@spring.message "tab.label.profile"/>
                    </a>
                </li>
                <li v-if="hasSchool && (profile.roles.schoolLead || profile.roles.schoolAdmin)">
                    <a href="#schoolTab" role="tab" data-toggle="tab" aria-expanded="true" >
                        <i class="material-icons">school</i>
                        <@spring.message "tab.label.school"/>
                    </a>
                </li>
                <li  v-show="profile.roles.organizer">
                    <a id="milongasTabLink" href="#milongasTab" role="tab" data-toggle="tab" aria-expanded="true">
                        <i class="material-icons">group</i>
                        <@spring.message "tab.label.milongas"/>
                    </a>
                </li>
                <li  v-show="profile.roles.organizer">
                    <a id="eventsTabLink" href="#eventsTab" role="tab" data-toggle="tab" aria-expanded="true">
                        <i class="material-icons">assistant_photo</i>
                        <@spring.message "tab.label.events"/>
                    </a>
                </li>
                <li  v-show="profile.roles.admin">
                    <a id="adminTabLink" href="#adminTab" role="tab" data-toggle="tab" aria-expanded="true">
                        <i class="material-icons">settings</i>
                        <@spring.message "tab.label.admin"/>
                    </a>
                </li>
            </ul>
            <div class="tab-content tab-space">
                <div role="tabpanel" class="tab-pane active" id="profileTab">
                    <#include "components/profileTab.ftl"/>
                </div>
                <div role="tabpanel" class="tab-pane" id="schoolTab" v-if="hasSchool">
                    <#include "components/schoolTab.ftl"/>
                </div>
                <div role="tabpanel" class="tab-pane" id="milongasTab">
                    <#include "components/milongasTab.ftl"/>
                </div>
                <div role="tabpanel" class="tab-pane" id="eventsTab">
                    <event-tab></event-tab>
                </div>
                <div role="tabpanel" class="tab-pane" id="adminTab">
                    <#include "components/adminTab.ftl"/>
                </div>
            </div>
        </div>
    </div>

    <room-modal></room-modal>
    <school-modal></school-modal>
    <event-modal></event-modal>
    <teacher-modal></teacher-modal>
    <profile-modal></profile-modal>
    <regular-lesson-modal></regular-lesson-modal>
    <single-lesson-modal></single-lesson-modal>
    <practice-modal></practice-modal>
    <milonga-modal></milonga-modal>
    <change-password-modal></change-password-modal>
    <image-select-modal id="profileAvatar" :ratio="1" size="AVATAR" :event="EventType.PROFILE_AVATAR_UPLOADED"></image-select-modal>
    <image-select-modal id="teacherAvatar" :ratio="1" size="AVATAR" :event="EventType.TEACHER_AVATAR_UPLOADED"></image-select-modal>
    <image-select-modal id="schoolPhoto" :ratio="3" size="SCHOOL_PHOTO" :event="EventType.SCHOOL_PHOTO_UPLOADED"></image-select-modal>
    <image-select-modal id="eventPhoto" :ratio="16/9" size="EVENT_PHOTO" :event="EventType.EVENT_PHOTO_UPLOADED"></image-select-modal>
    <image-select-modal id="milongaPhoto" :ratio="16/9" size="MILONGA_PHOTO" :event="EventType.MILONGA_PHOTO_UPLOADED"></image-select-modal>



    <div class="modal" id="chooseSchoolActivityModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content text-center">
                <div class="modal-header">
                    <h4 class="modal-title"><@spring.message "modal.title.schoolActivity"/></h4>
                </div>
                <div class="modal-body wide-buttons">
                    <button class="btn btn-lg btn-success" role="button" @click="addRegularLesson">
                        <@spring.message "activity.regularLesson"/>
                    </button>
                    <button class="btn btn-lg btn-primary" role="button" @click="addSingleSchoolLesson">
                        <@spring.message "activity.singleLesson"/>
                    </button>
                    <button class="btn btn-lg btn-info" role="button" @click="addPractice">
                        <@spring.message "activity.practice"/>
                    </button>
                </div>
            </div>
        </div>
    </div>

</div>
</#macro>

<@display_page "initCabinetPage"/>

portal/src/main/resources/ftl/dj_list.ftl
<#ftl encoding="UTF-8">

<#include "template.ftl"/>

<#macro components>
    <#include "components/form.ftl"/>

</#macro>

<#macro page_content>
<div class="wrapper" id="djList" v-cloak>

    <div class="container page-filter-panel">
        <div class="main main-raised">
            <div class="row">
                <div class="container-fluid">
                    <div class="col-md-12">
                        <h2 class="title"><@spring.message "page.title.djs"/></h2>
                        <form class="form">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group has-feedback is-empty label-floating">
                                        <label for="city" class="control-label"><@spring.message "common.city"/></label>
                                        <tp-city name="city" v-model="filter.city"></tp-city>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div id="map" style="height: 500px;">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container" v-if="isEmpty && firstLoaded">
        <div class="row">
            <div class="col-md-12">
                <div class="card text-center">
                    <div class="card-content content-warning">
                        <h3 class="card-title"><@spring.message "error.dj.notFoundInCity"/> {{filter.city.name}}.</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="grid">
            <div v-for="item in pageData.items" class="grid-item col-xs-12 col-md-3">
                <div class="grid-item-content">
                    <div class="card text-center">
                        <img :src="item.avatar" v-if="item.avatar" class="user-avatar">
                        <img src="/img/person_grey.png" v-if="!item.avatar" class="user-avatar">
                        <div class="card-content">
                            <h3 class="card-title">
                                {{item.firstName}} {{item.secondName}}
                            </h3>
                            <h4 class="card-title" v-if="item.djNick">
                                DJ {{item.djNick}}
                            </h4>
                            <h6 class="card-title" v-if="item.city">
                                {{item.city}}
                            </h6>
                            <div class="footer">
                                <a v-if="item.fbProfile" :href="item.fbProfile" target="_blank"
                                   class="btn btn-just-icon btn-facebook btn-round"><i
                                        class="fa fa-facebook-square"></i></a>
                                <a v-if="item.vkProfile" :href="item.vkProfile" target="_blank"
                                   class="btn btn-just-icon btn-vk btn-round"><i
                                        class="fa fa-vk"></i></a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</#macro>

<@display_page "initDjListPage"/>

portal/src/main/resources/ftl/faq.ftl
<#ftl encoding="UTF-8">

<#include "template.ftl"/>

<#macro page_content>
<div class="wrapper" id="index">
    <div class="container">

        <div class="main main-raised">
            <div class="row">
                <div class="container-fluid">
                    <div class="col-md-12">
                        <h2>Инструкция</h2>
                        <h3>Регулярные уроки</h3>
                        <p>Регулярные уроки - это те уроки, которые повторяются каждую неделю. При создании такого урока
                            необходимо указать дату с которой данный урок начнет повторяться (это день может не
                            совпадать с днем недели, в который урок непосредственно проводится). Также можно указать
                            дату окончания действия, если дата окончания не указана урок будет повторяться
                            бесконечно.
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

</#macro>

<@display_page />

portal/src/main/resources/ftl/index.ftl
<#ftl encoding="UTF-8">

<#include "template.ftl"/>

<#macro components>
    <#include "components/form.ftl"/>
</#macro>

<#macro page_content>
<div class="wrapper" id="index" v-cloak>
    <div class="container page-filter-panel">

        <div class="main main-raised">
            <div class="row">
                <div class="container-fluid">
                    <div class="col-md-12">
                        <h2 class="title"><@spring.message "page.title.playbill"/></h2>
                        <form class="form">
                            <div class="row">


                                <div class="col-md-6">
                                    <div class="form-group has-feedback is-empty label-floating">
                                        <label for="city" class="control-label"><@spring.message "common.city"/></label>
                                        <tp-city name="city" v-model="filter.city"></tp-city>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group has-feedback is-empty label-floating">
                                        <label for="from"
                                               class="control-label"><@spring.message "common.fromDate"/></label>
                                        <tp-date name="from" v-model="filter.from"></tp-date>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group has-feedback is-empty label-floating">
                                        <label for="to" class="control-label"><@spring.message "common.toDate"/></label>
                                        <tp-date name="from" v-model="filter.to"></tp-date>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div v-for="(day, dayIndex) in playbill.days" v-if="!isEmpty && firstLoaded"
                 :class="dayIndex % 2 == 0 ? 'section-gray' : 'section-light-gray'">
                <div class="container-fluid">
                    <div>
                        <h3 class="title">{{day.date | friendlyDate}} </h3>
                    </div>
                    <div class="grid">
                        <div v-for="event in day.events" class="grid-item col-md-4 col-sm-6 col-xs-12">
                            <div class="grid-item-content">
                                <div class="card md-card">
                                    <img v-if="event.photo" :src="event.photo" class="playbill-activity-photo">
                                    <div class="card-content" :class="getCardClass(event.type)">
                                        <h4 class="card-title">{{getEventName(event)}}</h4>
                                        <h6><a :href="'/school/' + event.schoolId">{{event.schoolName}}</a></h6>

                                        <div class="footer">
                                            <template v-if="event.type == 'LESSON'">
                                                <div class="tp-stats" v-if="event.firstTeacherId">
                                                    <i class="material-icons">group</i>
                                                    <span>{{playbill.teachers[event.firstTeacherId].firstName}} {{playbill.teachers[event.firstTeacherId].secondName}}</span>
                                                    <span v-if="event.secondTeacherId"> и {{playbill.teachers[event.secondTeacherId].firstName}} {{playbill.teachers[event.secondTeacherId].secondName}}</span>
                                                </div>
                                            </template>

                                            <div class="tp-stats" v-if="event.dj">
                                                <i class="material-icons">headset</i>
                                                DJ <span
                                                    v-if="event.dj.nick">{{event.dj.nick}} ({{event.dj.fullName}})</span>
                                                <span v-if="!event.dj.nick">{{event.dj.fullName}}</span>
                                            </div>

                                            <div class="tp-stats">
                                                <i class="material-icons">today</i> {{day.date | friendlyDate}}
                                            </div>

                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="tp-stats">
                                                        <i class="material-icons">schedule</i> {{event.startTime}}<span > -
                                                        {{event.endTime ? event.endTime : 'N/A'}}</span>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="tp-stats" v-if="event.cost > 0">
                                                        <i class="material-icons">attach_money</i> {{event.cost}}
                                                        {{event.currency}}
                                                    </div>
                                                </div>
                                            </div>


                                            <div class="tp-stats" v-if="event.address && event.address.pid != 0">
                                                <i class="material-icons">room</i> {{event.address.value}}
                                            </div>

                                            <a :href="event.fbUrl" v-if="event.fbUrl" target="_blank">
                                                <span class="fa-stack fa-lg">
                                                    <i class="fa fa-square-o fa-stack-2x"></i>
                                                    <i class="fa fa-facebook fa-stack-1x"></i>
                                                </span>
                                            </a>

                                            <a :href="event.vkUrl" v-if="event.vkUrl" target="_blank">
                                                <span class="fa-stack fa-lg">
                                                    <i class="fa fa-square-o fa-stack-2x"></i>
                                                    <i class="fa fa-vk fa-stack-1x"></i>
                                                </span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container" v-if="isEmpty && firstLoaded">
        <div class="row">
            <div class="col-md-12">
                <div class="card text-center">

                    <div class="card-content content-warning">
                        <h3 class="card-title"><@spring.message "error.activity.notFoundInCity"/>
                            {{filter.city.name}}.</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</#macro>

<@display_page "initIndexPage"/>

portal/src/main/resources/ftl/login.ftl
<#ftl encoding="UTF-8">

<#include "template.ftl"/>
<#import "spring.ftl" as spring/>

<#macro page_content>
<div class="wrapper" id="login">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-4 col-md-offset-4">
                <div class="main main-raised">
                    <div class="container-fluid">
                        <form role="form" id="loginPageForm" action="/login" method="POST" class="login-form">
                            <h2 class="title"><@spring.message "page.title.login"/></h2>

                            <div class="col-md-12">
                                <div class="alert alert-warning" v-if="error">
                                    <div class="container">
                                        <div class="alert-icon">
                                            <i class="material-icons">warning</i>
                                        </div>

                                        <span>{{'ERROR_' + error | translate}}</span>
                                    </div>
                                </div>

                                <div class="input-group">
								<span class="input-group-addon">
									<i class="material-icons">email</i>
								</span>
                                    <div class="form-group is-empty">
                                        <input class="form-control"
                                               type="text" v-model="username" placeholder="<@spring.message 'common.email'/>">
                                        <span class="material-input"></span>
                                    </div>
                                </div>

                                <div class="input-group">
								<span class="input-group-addon">
									<i class="material-icons">lock_outline</i>
								</span>
                                    <div class="form-group is-empty">
                                        <input class="form-control"
                                               type="password" v-model="password" placeholder="<@spring.message 'common.password'/>">
                                        <span class="material-input"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="text-center">
                                    <button class="btn btn-primary btn-simple btn-wd btn-lg" type="submit">
                                        <@spring.message "button.label.login"/>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<#if Session.url_prior_login??>
    <script>
        alert(${Session.url_prior_login});
    </script>
</#if>

</#macro>

<@display_page "initLoginPage"/>

portal/src/main/resources/ftl/map.ftl
<#ftl encoding="UTF-8">

<#include "template.ftl"/>

<#macro page_content>
<div class="wrapper" id="tangoMap" v-cloak>
    <div class="container">
        <div class="main main-raised">
            <div class="row">
                <div class="container-fluid">
                    <div class="col-md-12">
                        <h2 class="title"><@spring.message "page.title.map"/></h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div id="map" style="height: 500px;">
                        <div id="schoolCityPopover" v-show="initialized">
                            <h2 class="popover-title">{{selectedMarker.name}}</h2>
                            <div class="popover-content text-center">
                                <a v-if="selectedMarker.schoolCount" :href="'./schools?city=' + selectedMarker.name" class="btn btn-sm btn-primary block"><@spring.message "nav.label.schools"/> ({{selectedMarker.schoolCount}})</a>
                                <a v-if="selectedMarker.activityCount" :href="'./?city=' + selectedMarker.name" class="btn btn-sm btn-info block"><@spring.message "nav.label.playbill"/> ({{selectedMarker.activityCount}})</a>
                                <a v-if="selectedMarker.djCount" :href="'./djs?city=' + selectedMarker.name" class="btn btn-sm btn-success block"><@spring.message "nav.label.djs"/> ({{selectedMarker.djCount}})</a>
                                <a v-if="selectedMarker.eventCount" :href="'./events'" class="btn btn-sm btn-warning block"><@spring.message "nav.label.events"/> ({{selectedMarker.eventCount}})</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</#macro>

<@display_page "initMapPage"/>

portal/src/main/resources/ftl/sitemap.ftl
<#ftl encoding="UTF-8">
<#-- @ftlvariable name="cities" type="java.util.List<org.satuban.tangoportal.portal.model.dto.SiteMapDto>" -->

<#import "spring.ftl" as spring/>
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<#list cities as siteMapCity>
    <url>
        <loc>${siteMapCity.url}</loc>
    </url>
</#list>
</urlset>